# Generated by Django 5.2 on 2025-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addres', models.CharField(max_length=254)),
                ('phone_number', models.TextField(max_length=12)),
                ('coffee_type', models.TextField(max_length=40)),
                ('weight', models.TextField(max_length=4)),
            ],
        ),
    ]
